language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: Rlbc3r2RjlKikQKTypBch272wuz1zYX9yPNCk8WT2Rs5nDby1OnwbKOBpD8RUI7c0Jz1uUjO60jec2xtXbDxm02rWal/zqzj99rlZUn/IyWcLe2V6NFHNCXvMlQfkYGwcL0WGF9szHh+Vu2l0VRjmLHJoFKAIsAkEVkaoL2W9CW/wxj8NBHxV2kcEd/CJYJkZ3yU6lkO3g0mapltG/AegmYl2DGIF4a09pyB9Zb6rw9Ub4e9aL7CsMbHFJrXIVfqHIDakDPzY1nWd8JwHILG4XyjIvQBksVXIH6ymFmbCPJuOLvDgeRJFhIoMrqnj1Ot4fadOTEc8Tt5XdAgckcHKqEzRtXs04TeQueq/kZNRp79GJxrCY8FN56avZI2cePk1IvgkL2k8zu66Nv6nd2baRCcc2MsJsJbIBf04K3oaodYHO8adNdZIdPNHm+cax56181k0ci3z8Qzy/5LzKsB+M5DtGL7SXx1N0CZ0guPkfnNyUxxpiS1NuAgkjLGqgAW9ggIuVWvonRhuh7bkBS8Tz1p7HmmEek4ubTWFWKuehz/ek36w1BGa9fgsIMmjZT+fL3yGNIePJm5QMnEgBleMlyW+ade2v3plzYRN4Ao5O+rlXJpua04h+h5XDxUNQXGVCrFwX4EltlDJCZImQf8Eu7zBDdGCpkf401Olw/5OJk=
  app: huddleintheplanetofape